// <auto-generated />
namespace FoodGenie.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddedcartiteminterfacerecipelisttoAppUserModelremovedcartmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedcartiteminterfacerecipelisttoAppUserModelremovedcartmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201810230753103_Added cartitem interface, recipelist to AppUserModel & removed cart model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
